In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [66]:
df1 = pd.read_csv("city_day.csv")

In [67]:
df1

City        Date  PM2.5   PM10     NO    NO2    NOx    NH3  \
0          Ahmedabad  2015-01-01    NaN    NaN   0.92  18.22  17.15    NaN   
1          Ahmedabad  2015-01-02    NaN    NaN   0.97  15.69  16.46    NaN   
2          Ahmedabad  2015-01-03    NaN    NaN  17.40  19.30  29.70    NaN   
3          Ahmedabad  2015-01-04    NaN    NaN   1.70  18.48  17.97    NaN   
4          Ahmedabad  2015-01-05    NaN    NaN  22.10  21.42  37.76    NaN   
...              ...         ...    ...    ...    ...    ...    ...    ...   
29526  Visakhapatnam  2020-06-27  15.02  50.94   7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38  74.09   3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91  65.73   3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64  49.97   4.05  29.26  18.80  10.03   
29530  Visakhapatnam  2020-07-01  15.00  66.00   0.40  26.85  14.05   5.20   

          CO    SO2      O3  Benzene  Toluene  Xylene   AQI    AQI_Bucket  
0       0.92  27.64  133.36     0.00     0.02    0.00   NaN           NaN  
1       0.97  24.55   34.06     3.68     5.50    3.77   NaN           NaN  
2      17.40  29.07   30.70     6.80    16.40    2.25   NaN           NaN  
3       1.70  18.59   36.08     4.43    10.14    1.00   NaN           NaN  
4      22.10  39.33   39.31     7.01    18.89    2.78   NaN           NaN  
...      ...    ...     ...      ...      ...     ...   ...           ...  
29526   0.47   8.55   23.30     2.24    12.07    0.73  41.0          Good  
29527   0.52  12.72   30.14     0.74     2.21    0.38  70.0  Satisfactory  
29528   0.48   8.42   30.96     0.01     0.01    0.00  68.0  Satisfactory  
29529   0.52   9.84   28.30     0.00     0.00    0.00  54.0  Satisfactory  
29530   0.59   2.10   17.05      NaN      NaN     NaN  50.0          Good  

[29531 rows x 16 columns]

In [68]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   City        29531 non-null  object 
 1   Date        29531 non-null  object 
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object 
dtypes: float64(13), object(3)
memory usage: 3.6+ MB


In [69]:
df1.shape

(29531, 16)

In [70]:
(df1.isnull().sum()/df1.shape[0]*100).sort_values(ascending=False)

Xylene        61.322001
PM10          37.723071
NH3           34.973418
Toluene       27.229014
Benzene       19.041008
AQI           15.851139
AQI_Bucket    15.851139
PM2.5         15.570079
NOx           14.171549
O3            13.619586
SO2           13.050692
NO2           12.139785
NO            12.129626
CO             6.972334
City           0.000000
Date           0.000000
dtype: float64

In [71]:
df = df1.dropna()

In [72]:
df

City        Date  PM2.5    PM10    NO    NO2    NOx    NH3  \
2123       Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72   
2124       Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28   
2125       Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91   
2126       Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42   
2127       Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25   
...              ...         ...    ...     ...   ...    ...    ...    ...   
29525  Visakhapatnam  2020-06-26   7.63   32.27  5.91  23.27  17.19  11.15   
29526  Visakhapatnam  2020-06-27  15.02   50.94  7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38   74.09  3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91   65.73  3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64   49.97  4.05  29.26  18.80  10.03   

         CO    SO2      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  
2123   0.12  15.24  127.09     0.20     6.50    0.06  184.0      Moderate  
2124   0.14  26.96  117.44     0.22     7.95    0.08  197.0      Moderate  
2125   0.11  33.59  111.81     0.29     7.63    0.12  198.0      Moderate  
2126   0.09  19.00  138.18     0.17     5.02    0.07  188.0      Moderate  
2127   0.16  10.55  109.74     0.21     4.71    0.08  173.0      Moderate  
...     ...    ...     ...      ...      ...     ...    ...           ...  
29525  0.46   6.87   19.90     1.45     5.37    1.45   47.0          Good  
29526  0.47   8.55   23.30     2.24    12.07    0.73   41.0          Good  
29527  0.52  12.72   30.14     0.74     2.21    0.38   70.0  Satisfactory  
29528  0.48   8.42   30.96     0.01     0.01    0.00   68.0  Satisfactory  
29529  0.52   9.84   28.30     0.00     0.00    0.00   54.0  Satisfactory  

[6236 rows x 16 columns]

In [73]:
df.isnull().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6236 entries, 2123 to 29529
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   City        6236 non-null   object 
 1   Date        6236 non-null   object 
 2   PM2.5       6236 non-null   float64
 3   PM10        6236 non-null   float64
 4   NO          6236 non-null   float64
 5   NO2         6236 non-null   float64
 6   NOx         6236 non-null   float64
 7   NH3         6236 non-null   float64
 8   CO          6236 non-null   float64
 9   SO2         6236 non-null   float64
 10  O3          6236 non-null   float64
 11  Benzene     6236 non-null   float64
 12  Toluene     6236 non-null   float64
 13  Xylene      6236 non-null   float64
 14  AQI         6236 non-null   float64
 15  AQI_Bucket  6236 non-null   object 
dtypes: float64(13), object(3)
memory usage: 828.2+ KB


In [75]:
df.sample(10)

City        Date   PM2.5    PM10     NO    NO2    NOx    NH3  \
3722        Amritsar  2018-12-08   69.19  153.63  34.65  37.59  70.23   9.95   
11598          Delhi  2018-10-01   65.78  177.08  30.83  40.86  47.61  31.58   
2475       Amaravati  2018-11-12   84.48  164.24  14.25  80.74  54.62   3.19   
3058       Amaravati  2020-06-17    8.73   18.33   4.64  16.26  11.66  10.30   
19781        Kolkata  2020-04-28    7.71   19.98   3.95   9.15  13.15  12.33   
25657          Patna  2020-04-28   12.37   39.29  66.20  11.68  58.88  11.30   
25555          Patna  2020-01-17  135.89  210.83  31.14  39.22  69.02  26.91   
28235  Visakhapatnam  2016-12-14   62.66  102.67   4.05  22.56  15.08  12.02   
28618  Visakhapatnam  2018-01-01   59.73   99.04   1.73  23.69  13.89  11.68   
15357      Hyderabad  2017-02-18   75.46  197.99  15.75  46.97  15.11  27.44   

         CO    SO2     O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  
3722   0.01   6.20  16.57     6.52     2.25    9.91  131.0      Moderate  
11598  1.13  12.70  38.52     3.29    45.58    0.04  148.0      Moderate  
2475   1.21  30.44  33.39     0.10     0.39    0.25  156.0      Moderate  
3058   0.38  17.54  29.47     0.09     0.54    0.20   36.0          Good  
19781  0.34   5.21  29.82     1.60     6.06    0.43   45.0          Good  
25657  0.39   8.63  31.79     0.55     3.05    0.14   98.0  Satisfactory  
25555  2.07  11.24  18.16     0.83     1.99    1.69  261.0          Poor  
28235  1.15  31.35  90.96     5.54     5.84    2.80  107.0      Moderate  
28618  0.95   5.75  95.39     2.70     3.67    0.66  131.0      Moderate  
15357  0.24  33.86  39.71     0.24     2.35    0.73  179.0      Moderate

In [76]:
df.isnull().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [77]:
air_quality = {}
for idx, quality in zip(range(1,len(df['AQI_Bucket'].unique())+1), df['AQI_Bucket'].unique()):
    air_quality[quality]= idx
air_quality

{'Moderate': 1,
 'Poor': 2,
 'Very Poor': 3,
 'Satisfactory': 4,
 'Good': 5,
 'Severe': 6}

In [78]:
df["Air_quality"]= df["AQI_Bucket"].map(air_quality)

C:\Users\admin\AppData\Local\Temp\ipykernel_26136\1252989526.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Air_quality"]= df["AQI_Bucket"].map(air_quality)


In [79]:
df

City        Date  PM2.5    PM10    NO    NO2    NOx    NH3  \
2123       Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72   
2124       Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28   
2125       Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91   
2126       Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42   
2127       Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25   
...              ...         ...    ...     ...   ...    ...    ...    ...   
29525  Visakhapatnam  2020-06-26   7.63   32.27  5.91  23.27  17.19  11.15   
29526  Visakhapatnam  2020-06-27  15.02   50.94  7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38   74.09  3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91   65.73  3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64   49.97  4.05  29.26  18.80  10.03   

         CO    SO2      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  \
2123   0.12  15.24  127.09     0.20     6.50    0.06  184.0      Moderate   
2124   0.14  26.96  117.44     0.22     7.95    0.08  197.0      Moderate   
2125   0.11  33.59  111.81     0.29     7.63    0.12  198.0      Moderate   
2126   0.09  19.00  138.18     0.17     5.02    0.07  188.0      Moderate   
2127   0.16  10.55  109.74     0.21     4.71    0.08  173.0      Moderate   
...     ...    ...     ...      ...      ...     ...    ...           ...   
29525  0.46   6.87   19.90     1.45     5.37    1.45   47.0          Good   
29526  0.47   8.55   23.30     2.24    12.07    0.73   41.0          Good   
29527  0.52  12.72   30.14     0.74     2.21    0.38   70.0  Satisfactory   
29528  0.48   8.42   30.96     0.01     0.01    0.00   68.0  Satisfactory   
29529  0.52   9.84   28.30     0.00     0.00    0.00   54.0  Satisfactory   

       Air_quality  
2123             1  
2124             1  
2125             1  
2126             1  
2127             1  
...            ...  
29525            5  
29526            5  
29527            4  
29528            4  
29529            4  

[6236 rows x 17 columns]

In [80]:
city_idx = {}
for idx, city_n in zip(range(1,len(df['City'].unique())+1), df['City'].unique()):
    city_idx[city_n]= idx
city_idx

{'Amaravati': 1,
 'Amritsar': 2,
 'Chandigarh': 3,
 'Delhi': 4,
 'Gurugram': 5,
 'Hyderabad': 6,
 'Kolkata': 7,
 'Patna': 8,
 'Visakhapatnam': 9}

In [81]:
df['City']=df['City'].map(city_idx)

C:\Users\admin\AppData\Local\Temp\ipykernel_26136\4253501297.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City']=df['City'].map(city_idx)


In [82]:
df

City        Date  PM2.5    PM10    NO    NO2    NOx    NH3    CO  \
2123      1  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72  0.12   
2124      1  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28  0.14   
2125      1  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91  0.11   
2126      1  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42  0.09   
2127      1  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25  0.16   
...     ...         ...    ...     ...   ...    ...    ...    ...   ...   
29525     9  2020-06-26   7.63   32.27  5.91  23.27  17.19  11.15  0.46   
29526     9  2020-06-27  15.02   50.94  7.68  25.06  19.54  12.47  0.47   
29527     9  2020-06-28  24.38   74.09  3.42  26.06  16.53  11.99  0.52   
29528     9  2020-06-29  22.91   65.73  3.45  29.53  18.33  10.71  0.48   
29529     9  2020-06-30  16.64   49.97  4.05  29.26  18.80  10.03  0.52   

         SO2      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  \
2123   15.24  127.09     0.20     6.50    0.06  184.0      Moderate   
2124   26.96  117.44     0.22     7.95    0.08  197.0      Moderate   
2125   33.59  111.81     0.29     7.63    0.12  198.0      Moderate   
2126   19.00  138.18     0.17     5.02    0.07  188.0      Moderate   
2127   10.55  109.74     0.21     4.71    0.08  173.0      Moderate   
...      ...     ...      ...      ...     ...    ...           ...   
29525   6.87   19.90     1.45     5.37    1.45   47.0          Good   
29526   8.55   23.30     2.24    12.07    0.73   41.0          Good   
29527  12.72   30.14     0.74     2.21    0.38   70.0  Satisfactory   
29528   8.42   30.96     0.01     0.01    0.00   68.0  Satisfactory   
29529   9.84   28.30     0.00     0.00    0.00   54.0  Satisfactory   

       Air_quality  
2123             1  
2124             1  
2125             1  
2126             1  
2127             1  
...            ...  
29525            5  
29526            5  
29527            4  
29528            4  
29529            4  

[6236 rows x 17 columns]

In [83]:
df = df.drop(["AQI_Bucket", "Date"], axis = 1)

In [84]:
df['id'] = list(range(1,6237))

In [85]:
df = df.set_index('id')

In [86]:
x = df.drop(["AQI","Air_quality"], axis = 1)
y = df["AQI"]
y2 = df["Air_quality"]

In [87]:
x.head(5)

City  PM2.5    PM10    NO    NO2    NOx    NH3    CO    SO2      O3  \
id                                                                        
1      1  81.40  124.50  1.44  20.50  12.08  10.72  0.12  15.24  127.09   
2      1  78.32  129.06  1.26  26.00  14.85  10.28  0.14  26.96  117.44   
3      1  88.76  135.32  6.60  30.85  21.77  12.91  0.11  33.59  111.81   
4      1  64.18  104.09  2.56  28.07  17.01  11.42  0.09  19.00  138.18   
5      1  72.47  114.84  5.23  23.20  16.59  12.25  0.16  10.55  109.74   

    Benzene  Toluene  Xylene  
id                            
1      0.20     6.50    0.06  
2      0.22     7.95    0.08  
3      0.29     7.63    0.12  
4      0.17     5.02    0.07  
5      0.21     4.71    0.08

In [88]:
y[:10]

id
1     184.0
2     197.0
3     198.0
4     188.0
5     173.0
6     165.0
7     191.0
8     191.0
9     227.0
10    168.0
Name: AQI, dtype: float64

In [89]:
y2[:10]

id
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     2
10    1
Name: Air_quality, dtype: int64

In [90]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_scaled = sc.fit_transform(x)
x_scaled[:2]

array([[-1.63396921,  0.37375467,  0.01260924, -0.7773514 , -0.59673464,
        -0.7437744 , -0.62268395, -0.63739749,  0.51992943,  4.65229744,
        -0.69153128, -0.31121784, -0.55074012],
       [-1.63396921,  0.31640473,  0.06576563, -0.78633513, -0.30390943,
        -0.64262758, -0.65003535, -0.62264879,  2.15553585,  4.15874499,
        -0.68758008, -0.19319961, -0.54632968]])

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.30,random_state=35)

In [92]:
from sklearn.ensemble import RandomForestRegressor


In [93]:
rfc = RandomForestRegressor(n_estimators=100,max_depth = 10,random_state= 10).fit(X_train,y_train)

In [94]:
y_pred =rfc.predict(X_test)

In [95]:
y_pred

array([ 79.06739238,  41.88284811, 112.88679189, ...,  92.34018844,
       180.57152727, 155.91136648])

In [96]:
rfc.score(X_test,y_test)

0.9416701065305786

In [97]:
rfc.predict(sc.fit_transform(df.iloc[[22],:13]))

array([124.84621467])

In [101]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [102]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


mae =  mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2score = r2_score(y_test, y_pred)

print("Mean Absolute Error : ", mae)
print("Mean Squared Error : ", mse) 
print("Root Mean Squared Error : ", np.sqrt(mse))
print("R2 Score : ", r2score) 

Mean Absolute Error :  14.44452483990088
Mean Squared Error :  524.4805061119583
Root Mean Squared Error :  22.90153938301874
R2 Score :  0.9416701065305786


In [114]:
new_data =[[1,81,124,1.44,20,12,10,0.12,15,127,0.20,6.50,0.06]]
prediction=rfc.predict(sc.transform(new_data))
print(prediction)

[85.20588972]


c:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [103]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

#make pickle file of our model

In [98]:
import pickle

In [100]:
pickle.dump(rfc,open("model.pkl","wb"))

In [113]:
with open('model.pkl', 'rb') as f:
    rfc= pickle.load(f)
    

In [117]:
model = pickle.load(open('F:\\AQI ML Model\\model.pkl','rb'))

In [118]:
model.predict(sc.transform(new_data))

c:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([85.20588972])

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y2_train, y2_test = train_test_split(x_scaled, y2, test_size=0.05, random_state=27)

from sklearn.linear_model import LogisticRegression

In [109]:
lr = LogisticRegression(n_jobs=10)

In [110]:
lrm = lr.fit(X_train , y2_train)